#!/usr/bin/env python3
"""Create a deterministic, safely inventoried skill release archive."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import stat
import tempfile
import zipfile


def inventory(skill: Path) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    for path in sorted(skill.rglob("*")):
        mode = path.lstat().st_mode
        relative = path.relative_to(skill).as_posix()
        pure = PurePosixPath(relative)
        if pure.is_absolute() or ".." in pure.parts or "\\" in relative:
            raise ValueError(f"unsafe member path: {relative}")
        if "__pycache__" in pure.parts or path.suffix in {".pyc", ".pyo"}:
            raise ValueError(f"generated bytecode is not publishable: {relative}")
        if stat.S_ISLNK(mode):
            raise ValueError(f"symlink is not allowed: {relative}")
        if path.is_dir():
            continue
        if not stat.S_ISREG(mode):
            raise ValueError(f"special file is not allowed: {relative}")
        data = path.read_bytes()
        records.append(
            {
                "path": relative,
                "bytes": len(data),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    if not records or records[0]["path"] != "SKILL.md":
        if not (skill / "SKILL.md").is_file():
            raise ValueError("SKILL.md is missing")
    return records


def write_archive(skill: Path, output: Path, records: list[dict[str, object]]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.is_symlink() or output.parent.is_symlink():
        raise ValueError("output path must not use symlinks")
    fd, temporary_name = tempfile.mkstemp(prefix=f".{output.name}.", dir=output.parent)
    os.close(fd)
    temporary = Path(temporary_name)
    try:
        with zipfile.ZipFile(temporary, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
            for record in records:
                relative = str(record["path"])
                data = (skill / relative).read_bytes()
                info = zipfile.ZipInfo(f"{skill.name}/{relative}", (1980, 1, 1, 0, 0, 0))
                info.create_system = 3
                info.external_attr = (0o100644 & 0xFFFF) << 16
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, data)
        with zipfile.ZipFile(temporary) as archive:
            bad = archive.testzip()
            if bad is not None:
                raise ValueError(f"archive integrity failure at {bad}")
        os.replace(temporary, output)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("skill", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    skill = args.skill.resolve()
    output = args.output.resolve()
    records = inventory(skill)
    write_archive(skill, output, records)

    manifest_path = output.with_suffix(".manifest.json")
    manifest = {
        "schema_version": 1,
        "skill": skill.name,
        "files": records,
        "archive": {
            "path": output.name,
            "bytes": output.stat().st_size,
            "sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    digest_path = output.with_suffix(output.suffix + ".sha256")
    digest_path.write_text(f"{manifest['archive']['sha256']}  {output.name}\n")
    print(f"ARCHIVE={output}")
    print(f"FILES={len(records)}")
    print(f"BYTES={manifest['archive']['bytes']}")
    print(f"SHA256={manifest['archive']['sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
